FROM flink:1.17.0

# Install Python
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Ensure python command points to python3
RUN ln -s /usr/bin/python3 /usr/bin/python

# Copy the Kafka connector JAR to the Flink container
COPY flink-sql-connector-kafka-3.0.0-1.17.jar /opt/flink/lib/

# Install Python dependencies
RUN pip install nltk
RUN pip install rouge-score
# RUN pip install scikit-learn
# RUN pip install torch transformers
RUN python -m pip install apache-flink
RUN pip install prometheus_client

WORKDIR /app
COPY flink_main.py .

CMD ["python", "flink_main.py"]
